# -*- coding: utf-8 -*-
"""Botswana_Districts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1olLQqXwRDIrvcmGx0Ek600osRWgWBH6w
"""

!pip install geopandas
!pip install seaborn
#-------------------------------Load pacakges---------------------------------#
import os
import plotly.graph_objects as go
import geopandas as gpd
import seaborn as sns
import numpy as np
import matplotlib 
import matplotlib.pyplot as plt
import plotly.express as px
import pandas as pd
from google.colab import drive

drive.mount('/content/drive') #mounting the google drive
BWA_shape_pth = "/content/drive/MyDrive/Raw_data_sets/BW_shape/gadm40_BWA_1.shp" #the path to the shape file, currently available in this repo

BWA_shape = gpd.read_file(BWA_shape_pth) #read the the shape file for Botswana

#remove the cities and towns
BWA_shape_Clean = BWA_shape2.query("TYPE_1 == 'District'")
#print the panda with the shapes, you can modify it and add other layers/features of interest to you.
#BWA_shape_Clean



fig = matplotlib.pyplot.gcf()
fig.set_size_inches(8,8)
BWA_shape_Clean.plot(cmap = 'cool', edgecolor = 'black', figsize = (15,15))
plt.title('Botswana Districts')
plt.show()